# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

apiVersion: v1
description: Distribution of Fluentd as K8S daemonset
name: log-router
version: 0.4.0
home: https://github.com/vmware/kube-fluentd-operator
sources:
  - https://github.com/vmware/kube-fluentd-operator
